### ISSUE TITLE
Discovery integration tests failing on "yarn start"

### ISSUE THREAD

**Issue by lauracw100** [scrtlabs/salad#50]
This issue originated in the dev forum here: https://forum.enigma.co/t/salad-some-integration-tests-fail/1243

Summary:
Doing a fresh `git clone` of the _salad_ repo and following the README instructions up to and including `yarn start`, some of the integration tests fail.

Pull was done from the `develop` branch. Configuration used: `yarn configure-sw`.

<img width="872" alt="Screen Shot 2020-01-21 at 5 27 22 PM" src="https://user-images.githubusercontent.com/436905/72849601-0cb12e80-3c75-11ea-842b-3a626ed8d8a3.png">

Env:
```MacOS Catalina 10.15.1```
```Node: v11.15.0```
```rustc 1.38.0-nightly (8a58268b5 2019-07-31)```
```yarn: 1.19.2```
```docker: Docker version 19.03.5, build 633a0ea```
```docker-compose: docker-compose version 1.24.1, build 4667896b```

Troubleshooting:
Used this info to remove all docker images, including orphaned and dangling and re-tried the README steps: https://getintodevops.com/blog/keeping-the-whale-happy-how-to-clean-up-after-docker

The integration test failures were reproduced consistently.

Details:
- Six (6) out of the 14 integration tests fail with errors

```
Init tests › should check that 1 worker(s) and the principal node, and only them, are registered
client_1    | 
client_1    |     expect(received).toEqual(expected) // deep equality
client_1    | 
client_1    |     - Expected
client_1    |     + Received
client_1    | 
client_1    |     @@ -1,7 +1,7 @@
client_1    |       Array [
client_1    |     -   2,
client_1    |     +   0,
client_1    |         0,
client_1    |         0,
client_1    |         0,
client_1    |         0,
client_1    |         0,
```

```
 Init tests › should deposit tokens in worker banks
client_1    | 
client_1    |     Failed: "Returned error: VM Exception while processing transaction: revert Unregistered worker"
```

```
Init tests › should login the worker(s)
client_1    | 
client_1    |     : Timeout - Async callback was not invoked within the 20000ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 20000ms timeout specified by jest.setTimeout.Error
```

```
Init tests › should check that 1 worker(s), and only them, are logged in
client_1    | 
client_1    |     expect(received).toEqual(expected) // deep equality
client_1    | 
client_1    |     - Expected
client_1    |     + Received
client_1    | 
client_1    |     @@ -1,7 +1,7 @@
client_1    |       Array [
client_1    |     -   1,
client_1    |     +   0,
client_1    |         0,
client_1    |         0,
client_1    |         0,
client_1    |         0,
client_1    |         0,
```

```
Init tests › should get the worker parameters for the current block
client_1    | 
client_1    |     expect(received).toEqual(expected) // deep equality
client_1    | 
client_1    |     - Expected
client_1    |     + Received
client_1    | 
client_1    |     - Array [
client_1    |     -   "0x0000000000000000000000000000000000000000",
client_1    |     - ]
client_1    |     + Array []
```

```
Init tests › should create getTaskEncryptionKey from core (with call to P2P)
client_1    | 
client_1    |     : Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.Error:
```

**Comment by lauracw100** [comment]
Adding `yarn start` log output
[yarn-start.log](https://github.com/enigmampc/salad/files/4094199/yarn-start.log)

**Comment by fredfortier** [comment]
@lauraweindorf  This error occurs before any Salad tests. It fails on the basis system tests that discovery-cli runs. I'm not sure how to troubleshoot this at the moment. So, it is not an issue pertaining to this repo per se. Try doing a `discovery-cli` pull, and making sure the OP is using the same config parameters as you are.

**Comment by lauracw100** [comment]
Okay, thanks @fredfortier! 

I ended up resolving it by modifying the .env to use the 'latest' docker images instead of the 'develop' images.  I'll update the OP in the dev forum too.
